apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fullname }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
