apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullname }}-secret
type: Opaque
data:
  monitoring_username: {{ .Values.secret.data.Username | b64enc | quote }}
  monitoring_password: {{ .Values.secret.data.Password | b64enc | quote }}
