fullname: "monitoting-app"
name: "app"
lables: "app"
image:
  repository: "K8s_Using_HelmChart/monitoring-app"
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

service:
  name: monitoring-service
  type: ClusterIP
  port: 80
  targetPort: 8080

container:
  name: python-app

serviceAccount:
  create: true
  serviceAccountName: "developers_sg"
  automount: true
  annotations:
    exampleAnnotation: "Security_Group"

ingress:
  enabled: true
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - host: chart-example.local
      paths: 
        - path: /
          backend:
            serviceName: ingress
            servicePort: 8080

config:
  monitoring:
    apiEndpoint: "https://monitoring-api.example.com"
    apiKey: "##############################"
    pollingInterval: "5m"
  alerting:
    emailNotifications: true
    slackNotifications: false

secret:
  enabled: true
  data:
    username: "Bhanu_admin"
    password: "Admin@123"

persistentVolume:
  enabled: true
  size: 10Gi
  accessModes: "ReadWriteOnce"
  reclaimPolicy: "Retain"
  storageClassName: "local-storage"
  hostPath: "/data"

persistentVolumeClaim:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClassName: local-storage

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80